### ISSUE TITLE
Payment Option

### ISSUE THREAD

**Issue by Gh10User** [amonchakai/HFRBlack#12]
Help

**Comment by Gh10User** [comment]
I need help with a code, you could help me with the payment.qml? I want to deploy my app donation but do not know how to do and your Opensource out everything but that code, greetings.

**Comment by amonchakai** [comment]
Hi,

Just check the documentation, there are sample of code. I did not want to make public, the SKU of my own 'digital goods' that's why you don't have the corresponding qml. 
But frankly speaking, read the doc.
http://developer.blackberry.com/native/documentation/device_platform/paymentservice/settingup.html
